name: Basic Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
    Install-terraform:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Verify files
          run: ls -la

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
              terraform_version: 1.10.5

        - name: Terraform init
          run: terraform init