name: Basic Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
    Install-terraform:
        runs-on: ubuntu-latest
        steps:
            - run: sudo snap install terraform --classic
            - run: ls -la
            - run: terraform init
            - run: terraform plan
