name: Basic Actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
    Install-terraform:
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
            - run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
            - run: sudo apt update
            - run: sudo apt-get install terraform
            - run: terraform init
            - run: terraform plan
